#!/usr/bin/make -f

# Portions of this file contributed by NIST are governed by the
# following statement:
#
# This software was developed at the National Institute of Standards
# and Technology by employees of the Federal Government in the course
# of their official duties. Pursuant to Title 17 Section 105 of the
# United States Code, this software is not subject to copyright
# protection within the United States. NIST assumes no responsibility
# whatsoever for its use by other parties, and makes no guarantees,
# expressed or implied, about its quality, reliability, or any other
# characteristic.
#
# We would appreciate acknowledgement if the software is used.

SHELL := /bin/bash

top_srcdir := $(shell cd .. ; pwd)

uco_srcdir := $(top_srcdir)/dependencies/UCO

test_pys := $(wildcard test_*.py)

profile_ttls := $(wildcard $(top_srcdir)/ontology/uco-*.ttl)

shape_ttls := \
  $(wildcard $(top_srcdir)/dependencies/CDO-Shapes-gufo/shapes/sh-*.ttl) \
  $(wildcard $(top_srcdir)/shapes/sh-*.ttl)

all: \
  generated-exemplars-expanded.ttl

.pyshacl.done.log: \
  $(top_srcdir)/ontology/generated-ontology.ttl \
  $(top_srcdir)/shapes/generated-shapes.ttl \
  generated-exemplars-expanded.ttl
	source $(top_srcdir)/venv/bin/activate \
	  && pyshacl \
	    --ont-graph $(top_srcdir)/ontology/generated-ontology.ttl \
	    --shacl $(top_srcdir)/shapes/generated-shapes.ttl \
	    generated-exemplars-expanded.ttl
	touch $@

.pytest.done.log: \
  $(test_pys) \
  $(top_srcdir)/ontology/generated-ontology.ttl \
  exemplars.ttl
	source $(top_srcdir)/venv/bin/activate \
	  && pytest \
	    --log-level=DEBUG
	touch $@

check: \
  .pytest.done.log \
  .pyshacl.done.log

clean:
	@rm -rf \
	  __pycache__
	@rm -f \
	  .*.done.log \
	  generated-*

generated-exemplars-entailment.ttl: \
  $(top_srcdir)/.venv.done.log \
  $(top_srcdir)/ontology/generated-ontology.ttl \
  $(top_srcdir)/src/entail.py \
  exemplars.ttl
	source $(top_srcdir)/venv/bin/activate \
	  && python3 $(top_srcdir)/src/entail.py \
	    _$@ \
	    exemplars.ttl \
	    $(top_srcdir)/ontology/generated-ontology.ttl
	mv _$@ $@

generated-exemplars-expanded.ttl: \
  generated-exemplars-entailment.ttl
	source $(top_srcdir)/venv/bin/activate \
	  && rdfpipe \
	    --output-format turtle \
	    exemplars.ttl \
	    $< \
	    > _$@
	mv _$@ $@

monolithic.ttl: \
  $(top_srcdir)/.venv.done.log \
  $(profile_ttls) \
  $(shape_ttls)
	source $(top_srcdir)/venv/bin/activate \
	  && rdfpipe \
	    --output-format turtle \
	    $(top_srcdir)/dependencies/imports-transitive.ttl \
	    $(profile_ttls) \
	    $(shape_ttls) \
	    $(uco_srcdir)/tests/uco_monolithic.ttl \
	    > _$@
	source $(top_srcdir)/venv/bin/activate \
	  && pyshacl \
	    --shacl $(uco_srcdir)/ontology/owl/owl.ttl \
	    _$@
	# The monolithic build reviews itself, due to shapes pertaining to meta-classes.
	source $(top_srcdir)/venv/bin/activate \
	  && pyshacl \
	    --shacl _$@ \
	    _$@
	mv _$@ $@
